image: node:4.2.3

before_script:
  - npm config set spin false
  - npm install -g bower
  - npm install -g ember-cli
  - npm install -g phantomjs-prebuilt
  - npm install
  - bower install --allow-root

ember:
  script:
      - ember test
