version: '2'
services:
  resource-viewer:
    build: .
    command: npm install && ember server
    environment:
      NODE_ENV: development
      RESOURCE_CATALOGUER: http://localhost:3000
      DATA_COLLECTOR: http://localhost:4000
    command: server --watcher polling
    ports:
      - "4200:4200"
    volumes:
      - .:/resource-viewer
      - /resource-viewer/node_modules
      - /resource-viewer/bower_components

networks:
  default:
    external:
      name: platform
