#!/bin/sh

FILE_DIR=`perl -e 'use Cwd "abs_path";print abs_path(shift)' $0`
BASE_DIR=`dirname $FILE_DIR`/..

PROJECT_NAME="resource-viewer"
NETWORK="platform"
NET_ALIAS=$PROJECT_NAME
IMAGE_NAME="smart-cities/$PROJECT_NAME"
EXPOSED_PORT=4200

CYAN='\033[0;36m'
NC='\033[0m'
RED='\033[0;31m'

verify () {
  if [ $? != 0 ]; then
    echo "${RED}$1${NC}"
    exit 2
  fi
}

if [ "$1" = "start" ]; then
  echo "${CYAN}"
  echo "Starting service $PROJECT_NAME"
  echo "${NC}"

  sudo docker run  -d -v $BASE_DIR/:/$PROJECT_NAME/ --net=$NETWORK \
    --net-alias=$NET_ALIAS --name=$PROJECT_NAME -p $EXPOSED_PORT:4200 \
    $IMAGE_NAME
  verify "Cannot run the container. For more information take a look in docker's log"

  echo "${CYAN}"
  echo "############################################################"
  echo "     To execute commands in container you must run"
  echo "     $ scripts/development exec <command>"
  echo "############################################################"
  echo "${NC}"
fi

if [ "$1" = "stop" ]; then
  echo "${CYAN}"
  echo "Stopping service $PROJECT_NAME"
  echo "${NC}"

  sudo rm -rf $BASE_DIR/tmp/pids/*
  sudo docker kill $PROJECT_NAME 1> /dev/null
  sudo docker rm $PROJECT_NAME 1> /dev/null

  verify "You have some issue when we try to stop the container. Verify it manually"

  echo "${CYAN}"
  echo "####################################"
  echo "     The container is stopped."
  echo "####################################"
  echo "${NC}"
fi

if [ "$1" = "exec" ]; then
  echo "${CYAN}"
  echo "Executing command into the container's work directory"
  echo "${NC}"

  shift
  command="sudo docker exec $PROJECT_NAME"
 
	for word in $@; do
    command="$command $word"
  done

  $command
  verify "Cannot execute command into the container. Please verify logs"
fi
